# Bridge to pi5data central monitoring
connection pi5data
address pi5data:1883
remote_username emonpi
remote_password emonpimqtt2016
topic emon/# out 0
topic zigbee2mqtt/+  out 0
bridge_protocol_version mqttv311
start_type automatic
restart_timeout 10
